### ISSUE TITLE
Deployment setup

### ISSUE THREAD

**Issue by cfcortes** [BrightCoders-Proyectos/control-almacen#7]
# REQUIREMENT
Add deployment configuration to Heroku. The deployment must occur automatically every time a merge on master is executed.

# DESIGN

# Acceptance Criteria
- [x] Deployments to Heroku are automatically executed every time a marge on master is carried out.

**Comment by alx1313** [comment]
Heroku was implemented some days ago, but we got a problem after the merge of the last pull request, and i dont know how solve it. 
![Screenshot_2020-10-07 control-almacen-bc · Build Heroku](https://user-images.githubusercontent.com/51497719/95516745-549fef00-0985-11eb-897d-0770f04cd79b.png)
